README.md
This adds info to the README about custom features in Sandbox nodes that regular builds of nearcore do not have
=> docs: explain custom features

crate/.gitignore, crate/Cargo.toml, crate/build.rs, crate/src/lib.rs
Installs sandbox binary during runtime/test-time, to the following path format `{home}/.near/near-sandbox-{hash}/near-sandbox`
=> feat: install/init/start sandbox from rust

crate/Cargo.toml, crate/src/lib.rs
This will fix binaries from being corrupted from calling into `install`s concurrently. Different temp installation folders were added so that bytes weren't being written into the same one used for downloading. This solution was simpler thank a lockfile since that would've required some more complexity than I would've liked.
=> bugfix: avoid corrupting binaries near-sandbox binaries with different temp paths

crate/Cargo.toml
after this, will release 0.1.1 for `near-sandbox-utils` crate
=> release(crate): 0.1.1

crate/src/lib.rs
This adds a custom environment variable `NEAR_SANDBOX_LOG` to control log output of the sandbox binary which allows `workspaces-rs` to suppress logs going forward. This isn't exposing `RUST_LOG` to be used externally due to potentially conflicting with log targets that are potentially common such as `stats` from nearcore, which could end up as footgun.
Also, cleaned up some of the internal `target_os` command code since that seems to be consistent now.
=> feat(crate): Add in environment variables to control binary log output

crate/Cargo.toml
Newest patch release includes environment variables to allow configuring the sandbox binary's logs
=> release(crate): 0.1.2 sandbox crate release

crate/src/lib.rs
This is a simple change for now, but with https://github.com/near/workspaces-rs/issues/88, I can see us adding in builders in the future to do a lot of this configuration which could specify the download path and version, with potentially more to come.
=> feat(crate): Allow sandbox version configuration

crate/Cargo.toml, crate/src/lib.rs, crate/src/sync.rs
Fixes #29 
Decided to move sync functions to a separate module and expose async ones by default since this seems to be a common practice in Rust crates. Also, because you can't create a module named `async` :)
=> feat: support async calls for the rust crate

crate/Cargo.toml, crate/src/lib.rs, npm/dist/getBinary.js, npm/package.json, npm/src/getBinary.ts
This includes changes from https://github.com/near/sandbox/pull/28 to point to a closer nearcore binary.
@itegulov We have to point to master for the latest release since MacOS doesn't have a tagged binary quite yet, since this change was only recently done https://github.com/near/nearcore/pull/6426 and a new release (1.26 and up) will have to be made for it to be accessible
=> release(0.2) crate and release(0.0.9) npm package

crate/Cargo.toml, crate/src/lib.rs, npm/dist/getBinary.js, npm/package.json, npm/src/getBinary.ts
This should address https://github.com/near/workspaces-js/issues/170 on the sandbox side. `workspaces-js` still needs to update to this sandbox version. The `workspaces-rs` doesn't have to quite yet since it's just overriding to this version anyways
=> release: bump sandbox to 1.26.0

crate/Cargo.toml, crate/src/lib.rs
This is in preparation for release crate 0.4 with the M1 fix, which should come in the next patch version (0.4.1).
The biggest change is that we're no longer gonna have a compiler error when building on a non-supported platform, so that we can use the utility functions to call into an external provided binary if needed to. `workspaces-rs` shouldn't be affected too much by this since we're still gonna error out with `Unsupported platform` during build-time if the platform isn't supported or if the binary provided is wrong. Also, added a fix to not install when supplying incorrect path to the sandbox binary
Also, @austinabell do you think this should be pre-release? This crate isn't in the major versions yet so I feel it's not needed
=> release(crate): 0.4.0-pre.1

crate/Cargo.toml, crate/src/lib.rs, npm/dist/getBinary.js, npm/package.json, npm/src/getBinary.ts
This fixes inconsistent overflowing errors on nearcore binaries while on macOS
=> release: crate 0.4.1 and npm package 0.0.13

crate/Cargo.toml, crate/src/lib.rs, npm/dist/getBinary.js, npm/package.json, npm/src/getBinary.ts
This bumps sandbox nodes to the latest nearcore version as of Aug 29, 2022. Will make a crate/npm-package release after this
=> fix: gas allowance/estimation bug in sandbox

crate/Cargo.toml, crate/src/lib.rs, npm/package.json
For context and should resolve https://github.com/near/workspaces-rs/issues/193 after making it into workspaces-rs side.
After this PR, `ensure_sandbox_bin` will check if the binary is installable via a lockfile, so we don't run into any concurrent installs.
=> fix: Prevent installation from colliding when called concurrently into `ensure_sandbox_bin`

crate/src/lib.rs, npm/dist/getBinary.js, npm/src/getBinary.ts
Cleaner/Clearer to upgrade the hash commit to the latest release of nearcore instead of using arbitrary commits.
Pointing to https://github.com/near/nearcore/releases/tag/1.35.0
=> chore: point nearcore to latest release

crate/src/lib.rs
This improves perfomance of `cargo run --example nft` from `7.3s` to `3.80s`
=> speed things up

crate/Cargo.toml
There's was a [build issue](https://github.com/near/near-workspaces-rs/issues/312) with linux that started after the time `async-process v1.8.0` was [released](https://github.com/smol-rs/async-process/releases/tag/v1.8.0). This PR pins the package to the previous version. The issue concerned is left as a todo for later investigation/work.
`async-process` Issue: https://github.com/smol-rs/async-process/issues/55
=> fix: pin async-process crate

crate/src/lib.rs
The js sandbox utility makes use of `SANDBOX_ARTIFACT_URL` to override the binary download source. 
We apply this to the rust sandbox in this PR.
=> chore: use `SANDBOX_ARTIFACT_URL`

crate/src/lib.rs, npm/src/getBinary.ts
Update nearcore to v1.37.3 that adds `send_tx` RPC method and a some other features. This allows for `near-workspaces-js`, `near-api-js` and other dependants of near-sandbox to be compatible with the new RPC methods.
Currently near-api-js uses near-workspaces-js to run tests in a sandboxed environment. The latest PR updates the RPC logic to use `send_tx`. However the [CI checks](https://github.com/near/near-api-js/actions/runs/8247720893/job/22556700185#step:8:284) fails because: `[-32601] Method not found: send_tx`.
After this PR is updated, a subsequent PR will be opened in `near-workspaces-js` to bump the version, so that near-api-js can pull it.
=> Update nearcore version to post v1.37

Cargo.lock, crate/CHANGELOG.md, crate/Cargo.toml
* `near-sandbox-utils`: 0.7.0 -> 0.7.1 (✓ API compatible changes)
<blockquote>
- Update default nearcore version to v1.38.0 ([#81](https://github.com/near/near-sandbox/pull/81))
- use tokio instead of async-process as dependants use tokio runtime anyway ([#68](https://github.com/near/near-sandbox/pull/68))
- Expose DEFAULT_NEAR_SANDBOX_VERSION const
- run sandbox instance with --fast flag ([#56](https://github.com/near/near-sandbox/pull/56))
- Allow to specify verion of neard-sandbox ([#63](https://github.com/near/near-sandbox/pull/63))
- add aws link to rust crate ([#18](https://github.com/near/near-sandbox/pull/18))
- near-sandbox cargo crate for installing sandbox
- pin async-process crate …
=> chore: release v0.7.1

.github/workflows/tests.yml, crate/src/lib.rs, npm/src/getBinary.ts
It is not a breaking change since no API changes could break the old contracts or RPC clients.
=> chore: Updated the default neard version to 1.40.0

Cargo.lock, crate/CHANGELOG.md, crate/Cargo.toml
* `near-sandbox-utils`: 0.8.0 -> 0.9.0
<blockquote>
- Avoid different versions of near-sandbox binaries collision ([#72](https://github.com/near/near-sandbox/pull/72))
- Updated the default neard version to 1.40.0 ([#85](https://github.com/near/near-sandbox/pull/85))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).
=> chore: release v0.9.0

Cargo.lock, crate/CHANGELOG.md, crate/Cargo.toml
* `near-sandbox-utils`: 0.9.0 -> 0.10.0
<blockquote>
- [**breaking**] updated neard to 2.0.0 ([#88](https://github.com/near/near-sandbox/pull/88))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).
=> chore: release v0.10.0

Cargo.lock, crate/CHANGELOG.md, crate/Cargo.toml
* `near-sandbox-utils`: 0.10.0 -> 0.10.1
<blockquote>
- Updated near-sandbox to 2.1.1 ([#93](https://github.com/near/near-sandbox/pull/93))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).
=> chore: release v0.10.1

npm/.changeset/olive-years-suffer.md, npm/dist/getBinary.js, npm/dist/index.js, npm/package.json, npm/src/index.ts
- Updated the `download` method in `Binary` class to be asynchronous.
- Added a check to ensure the `installDir` directory exists before starting the download.
- If the directory does not exist, it is created with `fs.mkdir` using the `recursive` option.
- Add the `bin` folder in the npm package distribution, allowing necessary binaries to be available post-installation.
=> Ensure installation directory exists before downloading binary

Cargo.lock, crate/CHANGELOG.md, crate/Cargo.toml
* `near-sandbox-utils`: 0.11.0 -> 0.12.0 (✓ API compatible changes)
<blockquote>
- Updated near-sandbox version to 2.3.1 version ([#103](https://github.com/near/near-sandbox/pull/103))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).
=> chore: release v0.12.0

Cargo.lock, crate/CHANGELOG.md, crate/Cargo.toml
* `near-sandbox-utils`: 0.13.0 -> 0.14.0 (✓ API compatible changes)
<blockquote>
- [**breaking**] updates near-sandbox to nearcore 2.5.0 ([#109](https://github.com/near/near-sandbox/pull/109))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
=> chore: release v0.14.0

Cargo.lock, crate/CHANGELOG.md, crate/Cargo.toml
* `near-sandbox-utils`: 0.14.0 -> 0.15.0 (✓ API compatible changes)
<blockquote>
- [**breaking**] updates near-sandbox to nearcore 2.6.2 ([#112](https://github.com/near/near-sandbox/pull/112))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
=> chore: release v0.15.0
